name: deep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - pip
  - numpy
  - jupyterlab
  - h5py
  - matplotlib
  - pytest
  - scipy
  - scikit-learn
  - pip:
      - tensorflow-macos #v2.16.2
      - tensorflow-metal #v.1.2.0



